dubbo:
  application:
    name: product-service
  registry:
    protocol: zookeeper
    address: 192.168.137.89:2181
  protocol:
    port: 28801
server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lifestyle?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver